channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - pandas
  - notebook
  - cython
  - lxml
  - csvkit
  - ipywidgets
  - gdal
  - poppler
  - ipython-sql
  - pip:
    - bash_kernel
    - yq
    - requests-html
    - csvs-to-sqlite
    - goodtables
    - pyexcel-cli
    - daff
