channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - pandas
  - notebook
  - lxml
  - pip:
    - bash_kernel
    - yq
    - requests-html
    - csvs-to-sqlite
    - goodtables
    - pyexcel-cli
    - daff
